#!/usr/bin/env bash
set -euo pipefail

# Generated by gha-repro-kit.
# Run this from a clean checkout of the failing branch or commit.

echo "Primary job: Detect Agents SDK regressions"
echo "Primary step: pnpm --filter @openai/agents-core --filter @openai/agents-openai --filter @openai/agents add file:../../../openai-node/dist"

# CI environment hints:
# runner: ubuntu, ubuntu-24.04
# node: 22.22.3

pnpm --filter @openai/agents-core --filter @openai/agents-openai --filter @openai/agents add file:../../../openai-node/dist
