#!/usr/bin/env bash
set -euo pipefail

# Generated by gha-repro-kit.
# Run this from a clean checkout of the failing branch or commit.

echo "Primary job: Test Examples (20)"
echo "Primary step: docker run --rm -v $(pwd):/work mcr.microsoft.com/playwright:v1.35.1-focal /bin/bash -c \"cd /work && curl -s https://install-node.vercel.app/v20 | FORCE=1 bash && node -v && corepack enable > /dev/null && NEXT_TEST_JOB=1 NEXT_TEST_MODE=start xvfb-run node run-tests.js --type examples >> /proc/1/fd/1\""

# CI environment hints:
# runner: ubuntu, ubuntu-24.04
# node: 20.17.6

docker run --rm -v $(pwd):/work mcr.microsoft.com/playwright:v1.35.1-focal /bin/bash -c "cd /work && curl -s https://install-node.vercel.app/v20 | FORCE=1 bash && node -v && corepack enable > /dev/null && NEXT_TEST_JOB=1 NEXT_TEST_MODE=start xvfb-run node run-tests.js --type examples >> /proc/1/fd/1"
