#!/usr/bin/env bash
set -euo pipefail

# Generated by gha-repro-kit.
# Run this from a clean checkout of the failing branch or commit.

echo "Primary job: Lint 3.12"
echo "Primary step: uv sync --all-packages --group linting --all-extras"

# CI environment hints:
# runner: ubuntu, ubuntu-24.04
# python: 3.12

uv sync --all-packages --group linting --all-extras
