#!/usr/bin/env bash
set -euo pipefail

# Generated by gha-repro-kit.
# Run this from a clean checkout of the failing branch or commit.

echo "Primary job: lint"
echo "Primary step: Installed versions"

# CI environment hints:
# runner: ubuntu, ubuntu-24.04
# python: 3.15

echo "No command could be inferred from the log. Edit this script with the failing CI command."
