export function renderReport(analysis) {
  const target = analysis.target?.repo
    ? `${analysis.target.repo}${analysis.target.runId ? `#${analysis.target.runId}` : ""}${analysis.target.jobId ? ` job ${analysis.target.jobId}` : ""}`
    : "local log";
  const failure = analysis.primaryFailure;
  const command = selectReproductionCommand(analysis);

  return [
    "# GitHub Actions Failure Reproduction Report",
    "",
    `Target: ${target}`,
    `Primary job: ${failure.job}`,
    `Primary step: ${failure.step}`,
    failure.timestamp ? `Timestamp: ${failure.timestamp}` : null,
    `Failure: ${failure.message}`,
    isSpecificFailureClass(analysis.failureClass) ? `Failure class: ${analysis.failureClass.label}` : null,
    command ? `Likely command: \`${command}\`` : "Likely command: unknown",
    analysis.failureClass?.localRepro === false
      ? "Local repro: no direct local command; this appears to fail inside a GitHub Action step."
      : null,
    "",
    ...renderFailureClass(analysis.failureClass),
    "",
    "## CI Environment Hints",
    "",
    ...renderEnvironment(analysis.environment),
    "",
    "## Local Reproduction",
    "",
    analysis.failureClass?.localRepro === false
      ? "This failure appears to happen inside a GitHub Action setup step. Use the workflow action inputs and environment hints below to reproduce or adjust the CI configuration."
      : command
      ? "Run `./repro.sh` from a fresh checkout of the failing branch or commit."
      : "The log did not expose a runnable command. Inspect the context below and update `repro.sh`.",
    "",
    "## Failure Context",
    "",
    "```text",
    ...failure.context,
    "```",
    "",
    "## Commands Seen",
    "",
    ...renderCommands(analysis.commands),
    "",
    "## Jobs Seen",
    "",
    ...analysis.jobs.map((job) => `- ${job.job}: ${job.lines} log lines, ${job.steps.length} steps`),
    "",
    "## Maintainer Notes",
    "",
    "- Attach this report to the PR or issue when asking a contributor for follow-up.",
    "- Ask the contributor to run `./repro.sh` and paste the output if the failure does not reproduce locally.",
    "- If the failure is CI-only, compare the environment hints above with the contributor's local setup.",
  ]
    .filter((line) => line !== null)
    .join("\n");
}

export function renderSummary(analysis) {
  const failure = analysis.primaryFailure;
  const command = selectReproductionCommand(analysis);
  const runner = analysis.environment?.runner?.join(", ") || "unknown runner";
  const languages = Object.entries(analysis.environment?.languages ?? {})
    .map(([key, value]) => `${key} ${value}`)
    .join(", ");

  return [
    "## CI failure reproduction packet",
    "",
    `- Failed job: ${failure.job}`,
    `- Failed step: ${failure.step}`,
    `- Failure: ${failure.message}`,
    isSpecificFailureClass(analysis.failureClass) ? `- Failure class: ${analysis.failureClass.label}` : null,
    `- Likely command: ${command ? `\`${command}\`` : "unknown"}`,
    `- Environment: ${[runner, languages].filter(Boolean).join("; ")}`,
    "",
    "Maintainer handoff:",
    "",
    "1. Check `report.md` for the surrounding log context.",
    "2. Run `./repro.sh` from a clean checkout of the failing branch.",
    "3. If it does not reproduce, compare the CI environment hints against the local setup.",
  ]
    .filter((line) => line !== null)
    .join("\n");
}

export function renderReproScript(analysis) {
  const failure = analysis.primaryFailure;
  const command = selectReproductionCommand(analysis);

  return [
    "#!/usr/bin/env bash",
    "set -euo pipefail",
    "",
    "# Generated by gha-repro-kit.",
    "# Run this from a clean checkout of the failing branch or commit.",
    "",
    `echo "Primary job: ${escapeShellText(failure.job)}"`,
    `echo "Primary step: ${escapeShellText(failure.step)}"`,
    ...renderReproHints(analysis.environment),
    "",
    analysis.failureClass?.localRepro === false
      ? "echo \"No local command was inferred because the failure appears to be inside a GitHub Action setup step.\""
      : command
      ? command
      : "echo \"No command could be inferred from the log. Edit this script with the failing CI command.\"",
    "",
  ].join("\n");
}

function renderFailureClass(failureClass) {
  if (!isSpecificFailureClass(failureClass)) {
    return [];
  }

  const lines = ["## Failure Classification", "", `- Class: ${failureClass.label}`];
  if (failureClass.summary) {
    lines.push(`- Meaning: ${failureClass.summary}`);
  }

  if (failureClass.relatedCommands?.length) {
    lines.push("- Related commands:");
    for (const command of failureClass.relatedCommands) {
      lines.push(`  - \`${command}\``);
    }
  }

  if (failureClass.recommendations?.length) {
    lines.push("- Suggested checks:");
    for (const recommendation of failureClass.recommendations) {
      lines.push(`  - ${recommendation}`);
    }
  }

  return lines;
}

function isSpecificFailureClass(failureClass) {
  return Boolean(failureClass && failureClass.id !== "generic");
}

function renderEnvironment(environment = {}) {
  const lines = [];
  const runner = environment.runner ?? [];
  const languages = environment.languages ?? {};
  const matrix = environment.matrix ?? {};
  const setupSteps = environment.setupSteps ?? [];

  lines.push(runner.length ? `- Runner: ${runner.join(", ")}` : "- Runner: unknown");

  const languageEntries = Object.entries(languages);
  lines.push(
    languageEntries.length
      ? `- Language versions: ${languageEntries.map(([key, value]) => `${key} ${value}`).join(", ")}`
      : "- Language versions: unknown",
  );

  const matrixEntries = Object.entries(matrix);
  lines.push(
    matrixEntries.length
      ? `- Matrix hints: ${matrixEntries.map(([key, value]) => `${key}=${value}`).join(", ")}`
      : "- Matrix hints: none detected",
  );

  if (setupSteps.length) {
    lines.push("- Setup steps:");
    for (const step of setupSteps) {
      lines.push(`  - ${step.job} / ${step.step}`);
    }
  }

  return lines;
}

function renderReproHints(environment = {}) {
  const hints = [];
  const runner = environment.runner?.join(", ");
  const languages = Object.entries(environment.languages ?? {});

  if (runner || languages.length) {
    hints.push("");
    hints.push("# CI environment hints:");
    if (runner) hints.push(`# runner: ${runner}`);
    for (const [language, version] of languages) {
      hints.push(`# ${language}: ${version}`);
    }
  }

  return hints;
}

function renderCommands(commands) {
  if (!commands.length) {
    return ["- No runnable commands detected."];
  }

  return commands.map((command) => `- ${command.job} / ${command.step}: \`${command.command}\``);
}

function selectReproductionCommand(analysis) {
  if (analysis.failureClass?.localRepro === false) {
    return null;
  }

  const failure = analysis.primaryFailure;
  const sameStepCommands = analysis.commands.filter((command) => {
    return command.job === failure.job && command.step === failure.step && command.lineNumber <= failure.lineNumber;
  });

  if (sameStepCommands.length) {
    return sameStepCommands.at(-1).command;
  }

  return failure.nearestCommand?.command ?? analysis.commands.at(-1)?.command;
}

function escapeShellText(value) {
  return String(value).replaceAll('"', '\\"');
}
