#!/usr/bin/env bash
set -euo pipefail

# Generated by gha-repro-kit.
# Run this from a clean checkout of the failing branch or commit.

echo "Primary job: test (stable-s390x, ubuntu-latest, stable, s390x-unknown-linux-gnu)"
echo "Primary step: # In the past, new releases of 'cross' have broken CI. So for now, we"

# CI environment hints:
# runner: ubuntu, ubuntu-24.04
# rust: 1.96.0

tar xf cross-x86_64-unknown-linux-musl.tar.gz
